version: '3.3'

services:
  nginx:
    container_name: woodfarm
    image: nginx:1.18-alpine
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      domain: woodfarm.org
    restart: unless-stopped
    networks:
      - public
networks:
  public:
    external:
      name: public
